<a href="https://colab.research.google.com/github/daniyah-rehman/demo/blob/main/Pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Given Dictionary:-
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5,
np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes',
'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

a. Create and display a DataFrame from the above dictionary data which has
index labels.

b. Select and display the rows where the number of attempts in the
examination is greater than 2.

c. Count the number of rows and columns of the DataFrame.

d. Select the rows where the score is missing, i.e. is NaN.

e. Change the score in row 'd' to 11.5

f. Calculate the sum of the examination attempts by the students.

g. Append a new row 'k' to DataFrame with given values for each column.

Values for each column will be:
name : ‘Suresh’, score: 15.5, attempts: 1, qualify: ‘yes’; label: ‘k’
Now delete the new row and return the original data frame.

h. Sort the data frame first by 'name' in descending order, then by 'score' in
ascending order.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels =['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print(exam_data)
df = pd.DataFrame(exam_data, index=labels)
print(df)
print(df[df['attempts']>2])
df.sort_values('score')

{'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, nan, 9, 20, 14.5, nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

        name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes
d      James    NaN         3      no
h      Laura    NaN         1      no

In [ ]:
descending=df.sort_values('score',ascending= False)
print(descending)
rows=len(df.axes[0])
cols=len(df.axes[1])
print("Number of rows: "+ str(rows))
print("Number of cols: "+str(cols))

        name  score  attempts qualify
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
g    Matthew   14.5         1     yes
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
e      Emily    9.0         2      no
i      Kevin    8.0         2      no
d      James    NaN         3      no
h      Laura    NaN         1      no
Number of rows: 10
Number of cols: 4

In [ ]:
df[df['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

In [ ]:
df.loc['d','score']=11.5
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [ ]:
df['attempts'].sum()

19

In [ ]:
df.loc['k']=['Suresh',15.5,1,'yes']
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

Dataset: Use ‘Automobile_data.csv’

a. Load and Print first ten rows of the dataset.

b. Drop a column.

c. Print the last five rows.

d. Print All Toyota Cars details.

e. Count total cars per company

f. Find each company’s Highest priced car.

g. Get average mileage of all the cars.

h. Sort all cars by Price column

In [ ]:
df=pd.read_csv("Automobile_data.csv")
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.head(10)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110,19,18920.0
7,9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430.0
8,10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925.0
9,11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970.0

In [ ]:
df.drop(8)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110,19,18920.0
7,9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430.0
9,11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970.0
10,13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0
13,16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151.0
14,17,chevrolet,hatchback,94.5,155.9,ohc,four,70,38,6295.0
15,18,chevrolet,sedan,94.5,158.8,ohc,four,70,38,6575.0
16,19,dodge,hatchback,93.7,157.3,ohc,four,68,31,6377.0
17,20,dodge,hatchback,93.7,157.3,ohc,four,68,31,6229.0
18,27,honda,wagon,96.5,157.1,ohc,four,76,30,7295.0
19,28,honda,sedan,96.5,175.4,ohc,four,101,24,12945.0
20,29,honda,sedan,96.5,169.1,ohc,four,100,25,10345.0
21,30,isuzu,sedan,94.3,170.7,ohc,four,78,24,6785.0
22,31,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
23,32,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
24,33,jaguar,sedan,113.0,199.6,dohc,six,176,15,32250.0
25,34,jaguar,sedan,113.0,199.6,dohc,six,176,15,35550.0
26,35,jaguar,sedan,102.0,191.7,ohcv,twelve,262,13,36000.0
27,36,mazda,hatchback,93.1,159.1,ohc,four,68,30,5195.0
28,37,mazda,hatchback,93.1,159.1,ohc,four,68,31,6095.0
29,38,mazda,hatchback,93.1,159.1,ohc,four,68,31,6795.0
30,39,mazda,hatchback,95.3,169.0,rotor,two,101,17,11845.0
31,43,mazda,sedan,104.9,175.0,ohc,four,72,31,18344.0
32,44,mercedes-benz,sedan,110.0,190.9,ohc,five,123,22,25552.0
33,45,mercedes-benz,wagon,110.0,190.9,ohc,five,123,22,28248.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
36,49,mitsubishi,hatchback,93.7,157.3,ohc,four,68,37,5389.0
37,50,mitsubishi,hatchback,93.7,157.3,ohc,four,68,31,6189.0
38,51,mitsubishi,sedan,96.3,172.4,ohc,four,88,25,6989.0
39,52,mitsubishi,sedan,96.3,172.4,ohc,four,88,25,8189.0
40,53,nissan,sedan,94.5,165.3,ohc,four,55,45,7099.0
41,54,nissan,sedan,94.5,165.3,ohc,four,69,31,6649.0
42,55,nissan,sedan,94.5,165.3,ohc,four,69,31,6849.0
43,56,nissan,wagon,94.5,170.2,ohc,four,69,31,7349.0
44,57,nissan,sedan,100.4,184.6,ohcv,six,152,19,13499.0
45,61,porsche,hardtop,89.5,168.9,ohcf,six,207,17,34028.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
47,63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,NaN
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0
55,80,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7775.0
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.tail()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

In [ ]:
car_Manufacturers = df.groupby('company')
toyotaDf = car_Manufacturers.get_group('toyota')
toyotaDf

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [ ]:
car_Manufacturers = df.groupby('company')
priceDf = car_Manufacturers['company','price'].max()
priceDf

<ipython-input-89-20572cef35dd>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  priceDf = car_Manufacturers['company','price'].max()

                     company    price
company
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

In [ ]:
mileageDf = car_Manufacturers['company','average-mileage'].mean()
mileageDf

<ipython-input-90-7b16181cebd1>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mileageDf = car_Manufacturers['company','average-mileage'].mean()
<ipython-input-90-7b16181cebd1>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  mileageDf = car_Manufacturers['company','average-mileage'].mean()

               average-mileage
company
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

In [ ]:
df= df.sort_values(by=['price', 'horsepower'], ascending=False)
df.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0